// styles.ts
import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

const colors = theme.dark;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.surfaceVariant,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.onSurface,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: colors.primary,
    gap: 6,
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  infoSection: {
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: colors.surface,
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  infoTitle: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  infoText: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    lineHeight: 20,
    color: colors.onSurfaceVariant,
  },
  section: {
    borderRadius: 12,
    padding: 20,
    marginTop: 16,
    backgroundColor: colors.surface,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.onSurface,
  },
  addFieldButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: colors.accent,
    gap: 4,
  },
  addFieldText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: "Inter-SemiBold",
  },
  fieldCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: colors.surfaceVariant,
  },
  fieldHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  fieldNumber: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  removeFieldButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.error,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    marginBottom: 8,
    color: colors.onSurface,
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
    backgroundColor: colors.background,
  },
  fieldTypeContainer: {
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    backgroundColor: colors.surfaceVariant,
  },
  fieldTypeLabel: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    marginBottom: 8,
    color: colors.onSurface,
  },
  fieldTypeOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fieldTypeOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
    backgroundColor: colors.surface,
  },
  fieldTypeOptionText: {
    fontSize: 12,
    fontFamily: "Inter-Medium",
    color: colors.onSurface,
  },
  toggleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  toggleInfo: {
    flex: 1,
  },
  toggleTitle: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  toggleSubtitle: {
    fontSize: 12,
    fontFamily: "Inter-Regular",
    marginTop: 2,
    color: colors.onSurfaceVariant,
  },
  toggle: {
    width: 48,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    paddingHorizontal: 2,
    backgroundColor: colors.secondary,
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  optionsContainer: {
    marginTop: 8,
  },
  optionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  optionsLabel: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  addOptionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: colors.accent,
    gap: 4,
  },
  addOptionText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontFamily: "Inter-SemiBold",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  optionInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
    backgroundColor: colors.background,
  },
  removeOptionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.error,
  },
  previewSubtitle: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    marginBottom: 16,
    color: colors.onSurfaceVariant,
  },
  previewContainer: {
    borderRadius: 8,
    padding: 16,
    backgroundColor: colors.surface,
  },
  previewField: {
    marginBottom: 16,
  },
  previewFieldLabel: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    marginBottom: 6,
    color: colors.onSurface,
  },
  previewInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.background,
  },
  previewInputText: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
  },
  previewSelect: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.surfaceVariant,
  },
  previewSelectText: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
  },
  bottomSpacing: {
    height: 40,
  },
});
