import { theme } from "@/constants/theme";
import { StyleSheet } from "react-native";
const colors = theme.dark;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  loadingcontainer: {
    flex: 1,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    position: "relative",
    height: 300,
  },
  headerImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "space-between",
    padding: 20,
  },
  backButtonHeader: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    marginTop: 20,
  },
  headerContent: {
    flex: 1,
    justifyContent: "flex-end",
  },
  competitionBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.error,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 12,
  },
  competitionBadgeText: {
    color: colors.background,
    fontSize: 12,
    fontFamily: "Inter-SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  title: {
    fontSize: 28,
    fontFamily: "Inter-Bold",
    color: colors.background,
    lineHeight: 34,
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.background,
    marginLeft: 4,
  },
  reviewsText: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.border,
    marginLeft: 8,
  },
  actionButtons: {
    flexDirection: "row",
    padding: 20,
    paddingBottom: 10,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.error,
    gap: 8,
  },
  actionButtonText: {
    color: colors.error,
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
  },
  primaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.error,
    paddingVertical: 12,
    borderRadius: 8,
    gap: 8,
  },
  primaryButtonText: {
    color: colors.background,
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
  },
  section: {
    backgroundColor: colors.background,
    marginHorizontal: 20,
    marginBottom: 16,
    borderRadius: 12,
    padding: 20,
    shadowColor: colors.onSurface,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: "Inter-Bold",
    color: colors.onSurface,
    marginBottom: 16,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
    gap: 12,
  },
  detailContent: {
    flex: 1,
  },
  detailTitle: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    color: colors.secondary,
    marginBottom: 4,
  },
  detailText: {
    fontSize: 16,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
    lineHeight: 22,
  },
  detailSubtext: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurfaceVariant,
    marginTop: 2,
  },
  categorySection: {
    marginBottom: 20,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  categoryTitle: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  categoryScroll: {
    flexDirection: "row",
  },
  weightBadge: {
    backgroundColor: colors.surfaceVariant,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  weightText: {
    fontSize: 14,
    fontFamily: "Inter-Medium",
    color: colors.secondary,
  },
  prizeSection: {
    marginBottom: 20,
  },
  prizeHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  prizeTitle: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
  },
  prizeItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  prizePlace: {
    fontSize: 14,
    fontFamily: "Inter-Medium",
    color: colors.secondary,
    minWidth: 60,
  },
  prizeAmount: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
    flex: 1,
  },
  contactCard: {
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  contactName: {
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
    color: colors.onSurface,
    marginBottom: 2,
  },
  contactTitle: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    color: colors.onSurfaceVariant,
    marginBottom: 12,
  },
  contactActions: {
    flexDirection: "row",
    gap: 8,
  },
  contactButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.error,
    gap: 6,
  },
  contactButtonText: {
    color: colors.error,
    fontSize: 12,
    fontFamily: "Inter-SemiBold",
  },
  organizerContact: {
    backgroundColor: colors.onSurface,
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  organizerText: {
    fontSize: 14,
    fontFamily: "Inter-Medium",
    color: colors.background,
    marginBottom: 12,
  },
  organizerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.error,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 8,
  },
  organizerButtonText: {
    color: colors.background,
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 18,
    fontFamily: "Inter-SemiBold",
    color: colors.error,
    marginBottom: 20,
  },
  backButton: {
    backgroundColor: colors.error,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  backButtonText: {
    color: colors.background,
    fontSize: 16,
    fontFamily: "Inter-SemiBold",
  },
  bottomSpacing: {
    height: 20,
  },
});
