import { StyleSheet } from "react-native";
import { theme } from "@/constants/theme";

const colors = theme.dark;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.surfaceVariant,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    color: colors.onSurface,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    paddingHorizontal: 4,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  loadingText: {
    fontSize: 16,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
  },
  infoSection: {
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: colors.surface,
  },
  infoTitle: {
    fontSize: 18,
    fontFamily: "Inter-Bold",
    marginBottom: 8,
    color: colors.onSurface,
  },
  infoText: {
    fontSize: 14,
    fontFamily: "Inter-Regular",
    lineHeight: 20,
    color: colors.onSurfaceVariant,
  },
  formSection: {
    borderRadius: 12,
    padding: 20,
    marginTop: 16,
    backgroundColor: colors.surface,
  },
  fieldContainer: {
    marginBottom: 20,
  },
  fieldLabel: {
    fontSize: 14,
    fontFamily: "Inter-SemiBold",
    marginBottom: 8,
    color: colors.onSurface,
  },
  textInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
    backgroundColor: colors.surfaceVariant,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: colors.surfaceVariant,
  },
  dateInputText: {
    fontSize: 16,
    fontFamily: "Inter-Regular",
    flex: 1,
    color: colors.onSurface,
  },
  selectInput: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surfaceVariant,
  },
  selectInputText: {
    fontSize: 16,
    fontFamily: "Inter-Regular",
    flex: 1,
    color: colors.onSurface,
  },
  dropdown: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 200,
    backgroundColor: colors.surfaceVariant,
  },
  dropdownOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownOptionText: {
    fontSize: 16,
    fontFamily: "Inter-Regular",
    color: colors.onSurface,
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 6,
  },
  errorText: {
    fontSize: 12,
    fontFamily: "Inter-Regular",
    color: colors.error,
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 12,
    marginTop: 24,
    gap: 8,
    backgroundColor: colors.primary,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: "Inter-Bold",
  },
  bottomSpacing: {
    height: 40,
  },
});
